# Titles and introductory text
title: "RNA-seq"
subtitle: "QC analysis for RNA-seq data"
intro_text: "Multiple QC reports to summarise trimming and alignment."
report_comment: "This is the LaSalle lab version."

# Report Logo
custom_logo: '/share/lasallelab/programs/CpG_Me/UCDavis.png'
custom_logo_url: 'http://mmi-lab.ucdavis.edu/
custom_logo_title: 'LaSalle Lab @ UC Davis'

#Project level information
report_header_info:
    - Workflow Developer: 'Ben Laufer'
    - E-mail: 'blaufer@ucdavis.edu'
    - Application Type: 'RNA-seq'
    - Project Type: 'Pilot'
    - Sequencing Platform: 'NovaSeq 6000'
    - Sequencing Setup: 'PE 150 DI'
    - Library Kit: 'KAPA mRNA HyperPrep'
    - Genome: 'mm10'
